all:
  vars:
    ansible_user: root # Changed default to root or whatever user has SSH access
    # ansible_password: "password" # Uncomment if using password auth
    ansible_python_interpreter: /usr/bin/python3
  children:
    # All RabbitMQ nodes
    nodes:
      children:
        arizona:
        texas:

    # ============================================
    # Region: Arizona
    # 2 Availability Zones (~3ms metro)
    # ============================================
    arizona:
      children:
        az-cluster-1:
        az-cluster-2:

    # AZ-Cluster-1: 3 nodes (two in AZ1 and one in AZ2)
    az-cluster-1:
      vars:
        rmq_cluster_name: az-cluster-1
        cluster_seed: az-rmq-01
      hosts:
        pve-schwab-rmq01:
          ansible_host: 10.85.10.234 
          az_group: az_az1
        pve-schwab-rmq02:
          ansible_host: 10.85.10.235
          az_group: az_az1
        pve-schwab-rmq03:
          ansible_host: 10.85.10.236
          az_group: az_az2

    # AZ-Cluster-2: 3 nodes (one in AZ1 and two in AZ2)
    az-cluster-2:
      vars:
        rmq_cluster_name: az-cluster-2
        cluster_seed: az-rmq-04
      hosts:
        pve-schwab-rmq04:
          ansible_host: 10.85.10.241
          az_group: az_az1
        pve-schwab-rmq05:
          ansible_host: 10.85.10.242
          az_group: az_az2
        pve-schwab-rmq06:
          ansible_host: 10.85.10.243
          az_group: az_az2

    # ============================================
    # Region: Texas
    # 2 Availability Zones
    # ============================================
    texas:
      children:
        tx-cluster-1:

    # TX-Cluster-1: 3 nodes (two in AZ1 and one in AZ2)
    tx-cluster-1:
      vars:
        rmq_cluster_name: tx-cluster-1
        cluster_seed: tx-rmq-01
      hosts:
        pve-schwab-rmq07:
          ansible_host: 10.85.10.244
          az_group: tx_az1
        pve-schwab-rmq08:
          ansible_host: 10.85.10.245
          az_group: tx_az1
        pve-schwab-rmq09:
          ansible_host: 10.85.10.246
          az_group: tx_az2

    # Localhost for control tasks
    control:
      hosts:
        localhost:
          ansible_connection: local
